#!/usr/bin/python

import argparse, urllib, json

SERVER = ''
KEY = ''
PRINTERS = '/api/health/printers/'
PROTOCOL = 'http://'

parser = argparse.ArgumentParser()
parser.add_argument('--host','-H',type = str,help = 'Host address',required=True)
parser.add_argument('--printer','-p',type = str,help = 'Printer ID',required=True)
parser.add_argument('--key','-k',type = str,help = 'API authorization key',required=True)
parser.add_argument('--on_off_only','-O',action = 'store_true',help = 'Only report whether the printer is online or offline and omit all other performance data')
parser.add_argument('--secure','-S',action = 'store_true',help = 'Connect over HTTPS')

args = parser.parse_args()

SERVER = args.host
KEY = args.key
printerId = args.printer

if args.secure:
    PROTOCOL = 'https://'

url = PROTOCOL + SERVER + PRINTERS + printerId + '/status?Authorization=' + KEY

def load(url):
    response = urllib.urlopen(url)
    data = json.loads(response.read())
    return data

perfData = load(url)

status = perfData['status']

# Assume normal status unless otherwise specified
exitCode = 0
info = status

if status == 'OFFLINE':
    exitCode = 2
    info = 'Printer offline'
elif status == 'PAPER_JAM':
    if not args.on_off_only:
        exitCode = 1
        info = 'Paper jam'
else:
    exitCode = 3
    info = 'Unknown status'

print str(exitCode) + "|" + info + "\n"

exit(exitCode)
